name: gogame
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  pin_code_fields: ^3.1.2
  flutter_staggered_grid_view: ^0.3.0
  percent_indicator: ^2.1.5

  get_it: ^3.1.0
  provider_architecture: 1.0.3
  intl: ^0.16.1
  flag: ^2.0.3
  page_transition: ^1.1.5
  #  sms_autofill: ^1.2.1

  carousel_slider: ^2.1.0
  #  sliding_panel: ^1.2.3
  http: ^0.12.1
  device_info: ^0.4.2+4
  #  flutter_secure_storage: ^3.3.3
  dotted_border: ^1.0.5
  fimber: 0.4.2
  permission_handler: 5.0.1+1
  flutter_image_compress: 0.7.0
  #  google_maps_flutter: 0.5.28+1
  #  location_permissions: 3.0.0+1
  #  location: 3.0.2
  #  geocoder: 0.2.1
  #  flutter_facebook_login: 3.0.0
  dio: ^3.0.9
  flushbar: 1.10.4
  #  flutter_cupertino_date_picker: 1.0.26+2
  cached_network_image: ^2.2.0+1
  font_awesome_flutter: 8.8.1
  image_picker: 0.6.7+4
  shared_preferences: ^0.5.8
  #  qr_flutter: 3.2.0
  url_launcher: 5.5.0
  #  share: 0.6.4+3
  #  esys_flutter_share: 1.0.2
  #  maps_launcher: 1.2.1
  connectivity: 0.4.9
  socket_io_client: 0.9.10+1
  flutter_swiper: 1.1.6
  provider: 3.2.0
  flutter_neumorphic: ^3.0.2
  datetime_picker_formfield: ^1.0.0

  smooth_star_rating: ^1.1.1
  flutter_datetime_picker: ^1.3.8
  social_share: ^2.0.5
  simple_tooltip: ^0.1.14
  super_tooltip: ^0.9.0
  material_design_icons_flutter: ^4.0.5345
  hexcolor: ^1.0.4
  analog_clock: ^0.0.1
dependency_overrides:
  flutter_svg: ^0.18.0
  flutter_rounded_date_picker: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: PiedraRegular
      fonts:
        - asset: assets/fonts/PiedraRegular.ttf
    - family: InterBlack
      fonts:
        - asset: assets/fonts/InterBlack.ttf
    - family: InterBold
      fonts:
        - asset: assets/fonts/InterBold.ttf
    - family: InterExtraBold
      fonts:
        - asset: assets/fonts/InterExtraBold.ttf
    - family: InterExtraLight
      fonts:
        - asset: assets/fonts/InterExtraLight.ttf
    - family: InterLight
      fonts:
        - asset: assets/fonts/InterLight.ttf
    - family: InterMedium
      fonts:
        - asset: assets/fonts/InterMedium.ttf
    - family: InterRegular
      fonts:
        - asset: assets/fonts/InterRegular.ttf
    - family: InterSemiBold
      fonts:
        - asset : assets/fonts/InterSemiBold.ttf
    - family: InterThin
      fonts:
        - asset: assets/fonts/InterThin.ttf
    - family: LEMONMILKMedium
      fonts:
        - asset: assets/fonts/LEMONMILKMedium.otf
    - family: LEMONMILKBold
      fonts:
        - asset: assets/fonts/LEMONMILKBold.otf