const Map<String, String> English = {
  // Login (Mobile)
  "hello": "Hello,",
  "mobile_no": "Mobile Number",
  "next": "Next",
  "already_user": "Already User?",
  "login_here": "Login Here",
  "username": "Username",
  "connect_to_the_internet": "Connect_to_the_Internet",
  "view_profile": "View Profile",
  "light_coin": "Light Coin",
  "level": "Level",
  "cash": "Cash",
  "featured": "Featured",
  "tournaments": "Tournaments",
  "slaw_it_up": "slaw it up!",
  "settings": "Settings",
  "feedback": "Feedback",
  "my_tournaments": "My Tournaments",
  "payments": "Payments",
  "invite ": "Invite ",
  "preferences": "Preferences",
  "privacy_policy": "Privacy Policy",
  "terms_conditions ": "Terms & conditions",
  "community_guidelines": "Community Guidelines",
  "legal": "Legal",
  "helpdesk": "Helpdesk",
  "faq": "FAQ's",
  "logout": "Logout",
  "subject": "Subject",
  "description": "Description",
  "submit": "Submit",
  "refer_friend": "Refer friend",
  "you_and_your_friend_gets": "you and your friend gets",
  "deposit_cash": "Deposit Cash",
  "how_it_works": "How it works",
  "your_referral_code": "Here's Your referral code",
  "refer_instantly": "Refer Instantly",
  "my_rewards": "My Rewards",
  "your_referrals": "Your Referrals",
  "join_tournaments": "Join Tournaments",
  "refer_now": "Refer Now",
  "you_referred": "You Referred",
  "you_won": "You Won",
  "view_tournament_history": "View Tournament History",
  "you_have_initiated": "You Have Initiated",
  "No": "No.",
  "transaction_name": "Transaction Name",
  "add_cash": "Add Cash",
  "your_deposit_cash": "Your Deposit Cash",
  "your_wining_cash": "Your Wining Cash",
  "withdrawel_cash": "Withdrawel Cash ",
  "your_bonus_cash": "Your Bonus Cash",
  "how_to_earn": "How to Earn",
  "light_coin_code": "Light Coin Code",
  "enter_light_code_here": "Enter Light Code Here",
  "finished": "Finished",
  "won": "Won",
  "entry_fee_paid": "Entry Fee Paid",
  "entry_fee": "Entry Fee",
  "filter": "Filter",
  "clear_all": "Clear All",
  "prize_pool": "Prize Pool",
  "tournament_type": "Tournament Type",
  "buffer": "Buffer",
  "non_buffer": "Non Buffer",
  "live_register": "Live Register",
  "pre_register": "Pre Register",
  "apply": "Apply",
  "how_can_do_better": "How Can We do better ?",
  "cover_photo": "Cover Photo",
  "view_cover_photo": "View Cover Photo",
  "delete_cover_photo": "Delete Cover Photo",
  "update_cover_photo": "Update Cover Photo",
  "profile_photo": "Profile Photo",
  "view_profile_photo": "View Profile Photo",
  "delete_profile_photo": "Delete Profile Photo",
  "update_profile_photo": "Update Profile Photo",
  "my_zodiac ": "My Zodiac",
  "lives_in": "Lives In",
  "email": "email",
  "verify": "Verify",
  "edit_profile": "Edit Profile",
  "upload ": "upload ",
  "your_zodiac_sign": "Your Zodiac Sign",
  "you_stay_in": "You Stay in",
  "Date_of_birth": "Date-of-birth",
  "bio": "Bio",
  "upload_your_kyc": "Upload Your KYC",
  "my_number": "My Number",
  "choose_your_kyc": "Choose Your KYC",
  "my_kyc_number": "My KYC Number",
  "upload_your_selfie": "Upload Your Selfie",
  "change_visibility ": "Change Visibility",
  "Public": "Public",
  "my_followers": "My Followers",
  "only_me": "Only Me",
  "kyc_rules": " KYC Rules",
  "kyc_rules_description_one": "Your KYC is mandatory for Withdrawals .",
  "kyc_rules_description_two": "Your data is not stored bu GOGAME",
  "kyc_rules_description_three":
      "It takes 4 Hours to 3 Working Days to Verify your KYC",
  "kyc_rules_description_four": "In case of any grievances contact",
  "kyc_rules_description_support_link": "support@gogame.in",
  "privacy_policy_one": "We won't sharte your dat with anyone",
  "privacy_policy_two": "You have complete freedom of your data",
  "privacy_policy_three":
      "If you feel to rask for any data related issues, please feel to e-mail us at data@gogame.in",
  "remove_cover_photo_popup": "Are you sure want to remove your Cover Photo",
  "yes": "Yes",
  "no": "No",
  "prize_distribution": "prize_distribution",
  "leaderboard": "Leaderboard",
  "type": "Type",
  "join_more": "Join More",
  "terms_conditions_one": "Register Start @ 10:00 a.m.",
  "terms_conditions_two"
      "Registeration ends at 11:00 a.m."
      "terms_conditions_three": "You can join anytime you want in this contest",
  "terms_conditions_four": "you can play this contest only once",
  "terms_conditions_five": "You can even join this contest even at last minute"
};

const Map<String, String> Swahili = {};
